api = "0.7"

[buildpack]
  id = "paketo-buildpacks/pipenv"
  name = "Paketo Buildpack for Pipenv"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pipenv/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    checksum = "sha256:ea6ffd18e42eb7b6193c9bd820db8da934b25a406d9a28c33e76cdabc9ed93a9"
    cpe = "cpe:2.3:a:python-pipenv:pipenv:2026.4.0:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2026.4.0?checksum=ea6ffd18e42eb7b6193c9bd820db8da934b25a406d9a28c33e76cdabc9ed93a9&download_url=https://files.pythonhosted.org/packages/8b/1f/63c7e1f6877fa6c6e45e0512fc72ac7966a081fc333f851cea9081378fc7/pipenv-2026.4.0.tar.gz"
    source = "https://files.pythonhosted.org/packages/8b/1f/63c7e1f6877fa6c6e45e0512fc72ac7966a081fc333f851cea9081378fc7/pipenv-2026.4.0.tar.gz"
    source-checksum = "sha256:ea6ffd18e42eb7b6193c9bd820db8da934b25a406d9a28c33e76cdabc9ed93a9"
    stacks = ["*"]
    uri = "https://files.pythonhosted.org/packages/8b/1f/63c7e1f6877fa6c6e45e0512fc72ac7966a081fc333f851cea9081378fc7/pipenv-2026.4.0.tar.gz"
    version = "2026.4.0"

  [[metadata.dependencies]]
    checksum = "sha256:5402ac5fb1dae2c3d89e504496502da21fa38ff7c293b2e289a809e2f77b036e"
    cpe = "cpe:2.3:a:python-pipenv:pipenv:2026.5.0:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2026.5.0?checksum=5402ac5fb1dae2c3d89e504496502da21fa38ff7c293b2e289a809e2f77b036e&download_url=https://files.pythonhosted.org/packages/b6/67/fdc44f47b4fc9d99729c0e6588407642a4e8ec0d7522736cfe29fea4ebdf/pipenv-2026.5.0.tar.gz"
    source = "https://files.pythonhosted.org/packages/b6/67/fdc44f47b4fc9d99729c0e6588407642a4e8ec0d7522736cfe29fea4ebdf/pipenv-2026.5.0.tar.gz"
    source-checksum = "sha256:5402ac5fb1dae2c3d89e504496502da21fa38ff7c293b2e289a809e2f77b036e"
    stacks = ["*"]
    uri = "https://files.pythonhosted.org/packages/b6/67/fdc44f47b4fc9d99729c0e6588407642a4e8ec0d7522736cfe29fea4ebdf/pipenv-2026.5.0.tar.gz"
    version = "2026.5.0"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pipenv"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
