api = "0.7"

[buildpack]
  id = "paketo-buildpacks/pipenv"
  name = "Paketo Buildpack for Pipenv"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/pipenv/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    checksum = "sha256:e4fe303af2f13d29644081c905a28fe5a945ce75ea14310675baefafe7fdfab2"
    cpe = "cpe:2.3:a:python-pipenv:pipenv:2026.5.1:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2026.5.1?checksum=e4fe303af2f13d29644081c905a28fe5a945ce75ea14310675baefafe7fdfab2&download_url=https://files.pythonhosted.org/packages/8a/21/1657c31ed3df0b439f91f8f4c79abd8d6fa799a517918ec0153c5b3dc18c/pipenv-2026.5.1.tar.gz"
    source = "https://files.pythonhosted.org/packages/8a/21/1657c31ed3df0b439f91f8f4c79abd8d6fa799a517918ec0153c5b3dc18c/pipenv-2026.5.1.tar.gz"
    source-checksum = "sha256:e4fe303af2f13d29644081c905a28fe5a945ce75ea14310675baefafe7fdfab2"
    stacks = ["*"]
    uri = "https://files.pythonhosted.org/packages/8a/21/1657c31ed3df0b439f91f8f4c79abd8d6fa799a517918ec0153c5b3dc18c/pipenv-2026.5.1.tar.gz"
    version = "2026.5.1"

  [[metadata.dependencies]]
    checksum = "sha256:cf5985038a4cc4a1ffe9b48a2e580d2595245823dcc5684d07b1a53929ab47cc"
    cpe = "cpe:2.3:a:python-pipenv:pipenv:2026.5.2:*:*:*:*:python:*:*"
    id = "pipenv"
    licenses = ["MIT", "MIT-0"]
    name = "Pipenv"
    purl = "pkg:generic/pipenv@2026.5.2?checksum=cf5985038a4cc4a1ffe9b48a2e580d2595245823dcc5684d07b1a53929ab47cc&download_url=https://files.pythonhosted.org/packages/00/bf/9e5a536eae91adcbed6ee9c44861250bdfdc42bf2663680ce44cf5253fdb/pipenv-2026.5.2.tar.gz"
    source = "https://files.pythonhosted.org/packages/00/bf/9e5a536eae91adcbed6ee9c44861250bdfdc42bf2663680ce44cf5253fdb/pipenv-2026.5.2.tar.gz"
    source-checksum = "sha256:cf5985038a4cc4a1ffe9b48a2e580d2595245823dcc5684d07b1a53929ab47cc"
    stacks = ["*"]
    uri = "https://files.pythonhosted.org/packages/00/bf/9e5a536eae91adcbed6ee9c44861250bdfdc42bf2663680ce44cf5253fdb/pipenv-2026.5.2.tar.gz"
    version = "2026.5.2"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "pipenv"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
